version: '2'

services:
  # ============================= Rocketchat ==================================
  rocketchat:
    image: rocket.chat:latest
    restart: unless-stopped
    environment:
      - PORT=3000
      - ROOT_URL=${ROOT_URL}
      - MONGO_URL=${MONGO_URL}
      - ADMIN_USERNAME=${ROCKET_USER}
      - ADMIN_PASS=${ROCKET_PASS}
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128

  # ================================= Bot =====================================
  bot:
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    restart: unless-stopped
    environment:
      - MAX_TYPING_TIME=8
      - MIN_TYPING_TIME=1
      - WORDS_PER_SECOND_TYPING=10
      - ROCKETCHAT_URL=rocketchat:3000
      - ROCKETCHAT_ADMIN_USERNAME=${ROCKET_USER}
      - ROCKETCHAT_ADMIN_PASSWORD=${ROCKET_PASS}
      - ROCKETCHAT_BOT_USERNAME=${BOT_USER}
      - ROCKETCHAT_BOT_PASSWORD=${BOT_PASS}
      - ROCKETCHAT_BOT_EMAIL=${BOT_EMAIL}
      - ROCKETCHAT_BOT_NAME=${BOT_NAME}

      # Should be set to 'production' or 'beta' or 'dev'
      - ENVIRONMENT_NAME=${ENV_NAME}
      # Last commit hash using this command: git rev-parse HEAD
      - BOT_VERSION=0.1.0-alpha

    ports:
      - 5005:5005
      - 5002:5002
    depends_on:
      - actions
    volumes:
      - ./bot:/bot
      - ./scripts:/scripts

  actions:
    build:
      context: .
      dockerfile: ./docker/actions.Dockerfile
    # image: diegodorgam/botons:actions
    ports:
      - 5055:5055
    volumes:
      - ./bot/actions:/bot/actions
      - ./bot/Makefile:/bot/Makefile
    command: "make run-actions"

  jupyter:
    build:
      context: ./jupyter
      dockerfile: ./jupyter.Dockerfile
    ports:
      - 8888:8888
